### PR TITLE
[README.md] Adds variable example

### PR DESCRIPTION
**Pull request by kennethormandy**
This adds a gif of using a variable / GX font with a height axis if you happen to want it! I was trying it out anyway, and happy to see it worked.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thank you very much for adding this Kenneth!

**Comment by chrissimpkins** [comment]
I wasn't aware of this functionality.  Very nice :)

**Comment by chrissimpkins** [comment]
@kennethormandy are you using ttfa with variable fonts?

**Comment by kennethormandy** [comment]
No, I just happened to realise it was possible to view the result with this system. I will contribute back to the guide the best I can if I find out more!

**Comment by chrissimpkins** [comment]
@kennethormandy sounds good! thanks!

**Pull request merged**
